# Python Assignment 4 :Basic Statistics -2

In [2]:
import numpy as np
import pandas as pd

In [3]:
# loading data
patient = pd.read_csv("patient_Data.csv")
patient

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [4]:
patient.shape

(6, 7)

In [5]:
# info of dataset
patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [6]:
#finding nulls
patient.isna().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

In [7]:
# statistics
patient.describe()

        PatientID   BillAmount  ReceptionistID
count    6.000000     4.000000        6.000000
mean   102.666667  5925.000000        1.666667
std      1.632993  1192.686044        0.816497
min    101.000000  5000.000000        1.000000
25%    101.250000  5000.000000        1.000000
50%    102.500000  5600.000000        1.500000
75%    103.750000  6525.000000        2.000000
max    105.000000  7500.000000        3.000000

In [8]:
# droping unwanted columns
patient.drop(['ReceptionistID',	'CheckInTime'] , axis=1,inplace=True)

In [9]:
# grouping the data by dept
patient.groupby(['Department' , 'BillAmount']).sum()

                        PatientID        Name              Doctor
Department  BillAmount
Cardiology  5000.0            202  AliceAlice  Dr. SmithDr. Smith
            6200.0            104       David           Dr. Smith
Orthopedics 7500.0            103     Charlie             Dr. Lee

In [10]:
# droping the duplicates 
patient = patient.drop_duplicates(subset='Patient_ID')
patient

KeyError: Index(['Patient_ID'], dtype='object')

In [10]:
# filling the null values with mean 
patient['BillAmount'] = patient['BillAmount'].fillna(patient['BillAmount'].mean())

C:\Users\Thasin\AppData\Local\Temp\ipykernel_7728\1908236223.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  patient['BillAmount'] = patient['BillAmount'].fillna(patient['BillAmount'].mean())

In [11]:
patient

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [12]:
# loding billing dataset
billing = pd.read_csv('Billing_Data.csv')
billing

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [20]:
#concatenate
#pd.concat([patient, billing[['InsuranceCovered',	'FinalAmount']]] , axis=1)

In [21]:
# merging the two data set on basis of Patient_ID 
final_result = pd.merge(patient, billing, on='PatientID')
final_result

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [16]:

# final grouping the dept
patient.groupby(['Department', 'BillAmount']).sum()

                         PatientID     Name     Doctor
Department  BillAmount
Cardiology  5000.000000        101    Alice  Dr. Smith
            6200.000000        104    David  Dr. Smith
Dermatology 6233.333333        105      Eva   Dr. Rose
Neurology   6233.333333        102      Bob   Dr. John
Orthopedics 7500.000000        103  Charlie    Dr. Lee