# Python Assignment 9 : Data Preprocessing and Feature Engineering in Machine Learning

In [612]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt 
import seaborn as sns

In [613]:
data = pd.read_csv('adult_with_headers.csv')
data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [614]:
data.shape

(32561, 15)

In [615]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [616]:

data.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [617]:

X = data.drop('income', axis=1)  # all features
y = data['income']   # target

In [618]:
# identifying numerical and categorical columns

num_cols = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X.select_dtypes(include=['object']).columns
print(num_cols)
print(cat_cols)

Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week'],
      dtype='object')
Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country'],
      dtype='object')

In [619]:
# scaling the numerical data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])
# X[num_cols]

### 2. Encoding Techniques:

In [620]:
# encoding categorical data

# One-hot for small categories
one_hot_cols = [col for col in cat_cols if X[col].nunique() < 5]

# Label encoding for large categories
label_cols = [col for col in cat_cols if X[col].nunique() >= 5]

# One-hot
X = pd.get_dummies(X, columns=one_hot_cols, drop_first=True)

# Label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in label_cols:
    X[col] = le.fit_transform(X[col])

In [621]:
# encoding target column

le_y = LabelEncoder()
y = le_y.fit_transform(y)

In [622]:
data1 = pd.DataFrame(X, columns= data.columns)

In [623]:
y = pd.DataFrame(y, columns=['income>50k'])

In [624]:
data1 = X.join(y)

In [625]:
data1.shape

(32561, 15)

In [626]:
data1.describe()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,income>50k
count,3.256100e+04,32561.000000,3.256100e+04,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000,3.256100e+04,3.256100e+04,3.256100e+04,32561.000000,32561.000000
mean,-2.662271e-17,3.868892,-9.732565e-17,10.298210,1.479525e-16,2.611836,6.572740,1.446362,3.665858,5.237255e-18,-4.364379e-17,-2.574984e-17,36.718866,0.240810
std,1.000015e+00,1.455960,1.000015e+00,3.870264,1.000015e+00,1.506222,4.228857,1.606771,0.848806,1.000015e+00,1.000015e+00,1.000015e+00,7.823782,0.427581
min,-1.582206e+00,0.000000,-1.681631e+00,0.000000,-3.529656e+00,0.000000,0.000000,0.000000,0.000000,-1.459205e-01,-2.166595e-01,-3.194030e+00,0.000000,0.000000
25%,-7.757679e-01,4.000000,-6.816910e-01,9.000000,-4.200596e-01,2.000000,3.000000,0.000000,4.000000,-1.459205e-01,-2.166595e-01,-3.542945e-02,39.000000,0.000000
50%,-1.159546e-01,4.000000,-1.082193e-01,11.000000,-3.136003e-02,2.000000,7.000000,1.000000,4.000000,-1.459205e-01,-2.166595e-01,-3.542945e-02,39.000000,0.000000
75%,6.904838e-01,4.000000,4.478765e-01,12.000000,7.460392e-01,4.000000,10.000000,3.000000,4.000000,-1.459205e-01,-2.166595e-01,3.695194e-01,39.000000,0.000000
max,3.769612e+00,8.000000,1.226856e+01,15.000000,2.300838e+00,6.000000,14.000000,5.000000,4.000000,1.339458e+01,1.059351e+01,4.742967e+00,41.000000,1.000000

In [627]:
data.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [628]:
data1.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
sex_ Male         0
income>50k        0
dtype: int64

--> pros and cons of One-Hot Encoding.

*pros:
One-Hot Encoding
Works well with most ML models
Easy to understand

*cons:
Slower with large datasets
Not good for high-cardinality columns

--> pros and cons of Label Encoding.

*pros:
Simple and fast
Keeps dataset small

*cons:
Introduces false ordering
Can reduce model accuracy if misused

### 3. Feature Engineering:

In [629]:
# skewness

num_cols = ['age','fnlwgt','education_num','capital_gain',
                  'capital_loss','hours_per_week']
# num_cols = data.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    print(col,':', data1[col].skew())

age : 0.5587433694130483
fnlwgt : 1.4469800945789821
education_num : -0.31167586791023005
capital_gain : 11.95384768769979
capital_loss : 4.594629121679695
hours_per_week : 0.22764253680450094

In [630]:
# features 1
data1['total_capital'] = data['capital_gain'] - data['capital_loss']

In [631]:
# features 2
data1['hours_per_age'] = data['hours_per_week'] / data['age']

In [632]:
# skewness

real_num_cols = ['age','fnlwgt','education_num','capital_gain',
                 'capital_loss','hours_per_week',
                 'total_capital','hours_per_age']

for col in real_num_cols:
    print(col, data1[col].skew())

age 0.5587433694130483
fnlwgt 1.4469800945789821
education_num -0.31167586791023005
capital_gain 11.95384768769979
capital_loss 4.594629121679695
hours_per_week 0.22764253680450094
total_capital 11.87193391898442
hours_per_age 0.7475813949596964

In [633]:
# log function

data1['capital_gain_log'] = np.log1p(data['capital_gain'])

data1['capital_loss_log'] = np.log1p(data['capital_loss'])

data1['total_capital_log'] = np.log1p(data1['total_capital'])

data1['fnlwgt_log'] = np.log1p(data['fnlwgt'])

C:\Users\Thasin\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [634]:
# droping unwanted columns

data1.drop(['capital_gain', 'capital_loss', 'total_capital'], axis=1, inplace=True)

data1.drop('fnlwgt', axis=1, inplace=True)

In [635]:
# data1.head()

In [636]:
# skewness

num_cols = ['age','education_num','hours_per_week','hours_per_age',
                 'capital_gain_log','capital_loss_log','total_capital_log','fnlwgt_log']


for col in num_cols:
    print(col, data1[col].skew())

age 0.5587433694130483
education_num -0.31167586791023005
hours_per_week 0.22764253680450094
hours_per_age 0.7475813949596964
capital_gain_log 3.096143524467517
capital_loss_log 4.307536865725205
total_capital_log 3.001285314532635
fnlwgt_log -0.8424609456403455

#### --> 
     Skewness analysis was performed on  features , and the log functions are applied on high skwness features 
but the features like capital_loss_log changes moderately 

Thus the transformation improved the data for modeling pupose